[env:pico]
platform = raspberrypi
board = pico
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    adafruit/Adafruit DotStar
    https://github.com/adafruit/Adafruit_NeoPixel.git#1.15.0
    khoih-prog/LittleFS_Mbed_RP2040

build_flags =
    -D WOKWI_SIMULATION
