[env:pico]
platform = raspberrypi
board = pico
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    khoih-prog/LittleFS_Mbed_RP2040

build_flags =
    -w
